Repository edu-pi/Backend-Code-Analysis-Server, pull requests merged in 2024-07, with the labels that each got.

#110 [#95 #105]feat: AssignConverter를 사용해 AssignViz 생성 기능 추가
  app/visualize/code_visualizer.py
  app/visualize/generator/converter/assign_converter.py
  app/visualize/generator/converter_traveler.py
  app/visualize/generator/model/models.py
  tests/visualize/generator/converter/test_assign_converter.py
Labels: backend, decoupling, 테스트

#111 [Feat] Generator에서 for문 로직의 vizualize object 생성
  app/visualize/analysis/element_manager.py
  app/visualize/analysis/stmt/expr/model/range_expr_obj.py
  app/visualize/analysis/stmt/expr/parser/call_expr.py
  app/visualize/analysis/stmt/stmt_traveler.py
  app/visualize/code_visualizer.py
  app/visualize/generator/converter/for_converter.py
  app/visualize/generator/converter/print_converter.py
  app/visualize/generator/converter_traveler.py
  app/visualize/generator/convertor/for_header_convertor.py
  app/visualize/generator/highlight/for_highlight.py
  app/visualize/generator/highlight/highlight.py
  app/visualize/generator/model/models.py
  app/visualize/generator/visualization_manager.py
Labels: backend, decoupling

#112 [#109]fix: expr 관련 model들이 Expr Oject를 상속받아 구현되도록 수정
  app/visualize/analysis/stmt/expr/expr_traveler.py
  app/visualize/analysis/stmt/expr/expr_util/util.py
  app/visualize/analysis/stmt/expr/model/expr_obj.py
  app/visualize/analysis/stmt/expr/model/print_expr_obj.py
  app/visualize/analysis/stmt/expr/model/range_expr_obj.py
  app/visualize/analysis/stmt/expr/model/range_expression.py
  app/visualize/analysis/stmt/expr/parser/binop_expr.py
  app/visualize/analysis/stmt/expr/parser/call_expr.py
  app/visualize/analysis/stmt/expr/parser/constant_expr.py
  app/visualize/analysis/stmt/expr/parser/name_expr.py
  app/visualize/analysis/stmt/model/for_stmt_obj.py
  app/visualize/analysis/stmt/stmt_traveler.py
  app/visualize/generator/convertor/for_header_convertor.py
  tests/visualize/analysis/stmt/expr/parser/test_binop_expr.py
  tests/visualize/analysis/stmt/parser/test_expr_stmt.py
Labels: backend, decoupling

#113 [#104 #109] ExprConverter의 기능을 추가하고 109번에 대한 테스트 코드 작성
  app/visualize/analysis/stmt/expr/parser/constant_expr.py
  app/visualize/analysis/stmt/expr/parser/name_expr.py
  app/visualize/analysis/stmt/model/expr_stmt_obj.py
  app/visualize/analysis/stmt/parser/expr_stmt.py
  app/visualize/generator/converter/expr_converter.py
  app/visualize/generator/converter_traveler.py
  app/visualize/generator/model/models.py
  tests/visualize/analysis/stmt/expr/parser/test_call_expr.py
  tests/visualize/analysis/stmt/expr/parser/test_constant_expr.py
  tests/visualize/analysis/stmt/expr/parser/test_name_expr.py
  tests/visualize/analysis/stmt/parser/test_expr_stmt.py
  tests/visualize/generator/converter/test_expr_converter.py
Labels: feat, 테스트

#115 [#103]fix: body 분석 로직 주석 해제
  app/visualize/generator/converter/expr_converter.py
  app/visualize/generator/converter_traveler.py
Labels: backend, decoupling

#118 [#117]fix: call_id 로직으로 id를 생성하던 방식에서 lineno를 사용해 id를 생성하는 방식으로 변경
  app/analysis/generator/assign_generator.py
  app/analysis/generator/body_generator.py
  app/analysis/generator/expr_generator.py
  app/analysis/generator/for_generator.py
  app/visualize/analysis/stmt/expr/parser/call_expr.py
  app/visualize/analysis/stmt/model/assign_stmt_obj.py
  app/visualize/analysis/stmt/model/expr_stmt_obj.py
  app/visualize/analysis/stmt/model/for_stmt_obj.py
  app/visualize/analysis/stmt/parser/assign_stmt.py
  app/visualize/analysis/stmt/parser/expr_stmt.py
  app/visualize/analysis/stmt/parser/for_stmt.py
  app/visualize/generator/converter/assign_converter.py
  app/visualize/generator/converter/expr_converter.py
  app/visualize/generator/converter/for_header_converter.py
  app/visualize/generator/converter_traveler.py
  app/visualize/generator/highlight/highlight.py
  app/visualize/generator/model/models.py
  app/visualize/generator/visualization_manager.py
  tests/analysis/generator/__init__.py
  tests/analysis/generator/data/__init__.py
  tests/analysis/generator/data/test_assign_generator_data.py
  tests/analysis/generator/parser/__init__.py
  tests/analysis/generator/parser/test_binop_parser.py
  tests/analysis/generator/parser/test_call_parser.py
  tests/analysis/generator/parser/test_constant_parser.py
  tests/analysis/generator/parser/test_data/for_generator_data.py
  tests/analysis/generator/parser/test_name_parser.py
  tests/analysis/generator/parser/test_tuple_parser.py
  tests/analysis/generator/test_assign_generator.py
  tests/analysis/generator/test_for_generator.py
  tests/visualize/analysis/stmt/expr/parser/test_call_expr.py
  tests/visualize/analysis/stmt/parser/test_expr_stmt.py
  tests/visualize/generator/converter/test_assign_converter.py
  tests/visualize/generator/converter/test_expr_converter.py
Labels: fix

#131 [#124]feat: ListExpr 테스트 케이스에 맞게 기능 구현
  app/visualize/analysis/stmt/expr/model/expr_obj.py
  app/visualize/analysis/stmt/expr/parser/list_expr.py
  tests/visualize/analysis/stmt/expr/parser/test_list_expr.py
Labels: feat

#133 [#121]feat: ast.if를 분석해서 ifStmtObj 생성 로직 구현
  app/visualize/analysis/element_manager.py
  app/visualize/analysis/stmt/expr/parser/compare_expr.py
  app/visualize/analysis/stmt/model/if_stmt_obj.py
  app/visualize/analysis/stmt/parser/if_stmt.py
  app/visualize/analysis/stmt/stmt_traveler.py
  app/visualize/code_visualizer.py
Labels: backend, if-else

#135 [#39]feat: List 기능 구현
  app/visualize/analysis/stmt/expr/expr_traveler.py
  app/visualize/analysis/stmt/expr/model/expr_obj.py
  app/visualize/analysis/stmt/expr/parser/binop_expr.py
  app/visualize/analysis/stmt/expr/parser/list_expr.py
  app/visualize/analysis/stmt/expr/parser/name_expr.py
  app/visualize/analysis/stmt/model/assign_stmt_obj.py
  app/visualize/analysis/stmt/parser/assign_stmt.py
  app/visualize/analysis/stmt/parser/expr_stmt.py
  app/visualize/analysis/stmt/parser/for_stmt.py
  app/visualize/code_visualizer.py
  app/visualize/generator/converter/assign_converter.py
  app/visualize/generator/converter/expr_converter.py
  app/visualize/generator/converter/for_header_converter.py
  app/visualize/generator/highlight/expr_highlight.py
  app/visualize/generator/highlight/for_highlight.py
  app/visualize/generator/highlight/highlight.py
  app/visualize/generator/highlight/list_highlight.py
  app/visualize/generator/model/models.py
  tests/visualize/analysis/stmt/expr/parser/test_binop_expr.py
  tests/visualize/analysis/stmt/expr/parser/test_list_expr.py
  tests/visualize/analysis/stmt/expr/parser/test_name_expr.py
  tests/visualize/generator/converter/test_assign_converter.py
  tests/visualize/generator/highlight/test_expr_highlight.py
  tests/visualize/generator/highlight/test_highlight.py
  tests/visualize/generator/highlight/test_list_highlight.py
Labels: feat, backend

#139 [#74]feat: if, else 분석 기능 구현
  app/visualize/analysis/element_manager.py
  app/visualize/analysis/stmt/expr/expr_traveler.py
  app/visualize/analysis/stmt/expr/expr_util/util.py
  app/visualize/analysis/stmt/expr/model/expr_obj.py
  app/visualize/analysis/stmt/expr/parser/compare_expr.py
  app/visualize/analysis/stmt/model/if_stmt_obj.py
  app/visualize/analysis/stmt/parser/expr_stmt.py
  app/visualize/analysis/stmt/parser/if_stmt.py
  app/visualize/analysis/stmt/stmt_traveler.py
  app/visualize/code_visualizer.py
  app/visualize/generator/converter/assign_converter.py
  app/visualize/generator/converter/expr_converter.py
  app/visualize/generator/converter/for_header_converter.py
  app/visualize/generator/converter/if_converter.py
  app/visualize/generator/converter_traveler.py
  app/visualize/generator/highlight/for_highlight.py
  app/visualize/generator/model/assign_viz.py
  app/visualize/generator/model/expr_viz.py
  app/visualize/generator/model/for_viz.py
  app/visualize/generator/model/if_viz.py
  app/visualize/generator/model/models.py
  app/visualize/generator/model/print_viz.py
  app/visualize/generator/model/variable_vlz.py
  tests/visualize/analysis/stmt/expr/parser/test_compare_expr.py
Labels: backend, if-else

#140 [#137] assignGenerator에서 코드 흐름 부분을 만들고 있던 로직을 ExprGenerator로 통합, 테스트 커버리지 확인 라이브러리 추가
  app/visualize/analysis/stmt/expr/model/expr_obj.py
  app/visualize/analysis/stmt/expr/parser/list_expr.py
  app/visualize/analysis/stmt/model/assign_stmt_obj.py
  app/visualize/analysis/stmt/model/expr_stmt_obj.py
  app/visualize/analysis/stmt/parser/assign_stmt.py
  app/visualize/analysis/stmt/parser/expr_stmt.py
  app/visualize/generator/converter/assign_converter.py
  app/visualize/generator/converter/expr_converter.py
  app/visualize/generator/converter_traveler.py
  app/visualize/generator/highlight/list_highlight.py
  app/visualize/generator/model/variable_vlz.py
  app/visualize/utils/util.py
  poetry.lock
  pyproject.toml
  tests/visualize/analysis/stmt/expr/parser/test_binop_expr.py
  tests/visualize/analysis/stmt/expr/parser/test_call_expr.py
  tests/visualize/analysis/stmt/expr/parser/test_constant_expr.py
  tests/visualize/analysis/stmt/expr/parser/test_list_expr.py
  tests/visualize/analysis/stmt/expr/parser/test_name_expr.py
  tests/visualize/analysis/stmt/parser/test_assign_stmt.py
  tests/visualize/analysis/stmt/parser/test_expr_stmt.py
  tests/visualize/analysis/stmt/parser/test_for_stmt.py
  tests/visualize/generator/converter/test_assign_converter.py
  tests/visualize/generator/converter/test_expr_converter.py
  tests/visualize/generator/highlight/test_expr_highlight.py
  tests/visualize/generator/highlight/test_list_highlight.py
Labels: backend, refactor

#148 [#141]test: if-else parser 테스트 코드 작성
  app/visualize/analysis/stmt/parser/if_stmt.py
  app/visualize/analysis/stmt/stmt_traveler.py
  tests/visualize/analysis/stmt/parser/expr/parser/test_call_expr.py
  tests/visualize/analysis/stmt/parser/test_for_stmt.py
  tests/visualize/analysis/stmt/parser/test_if_stmt.py
  tests/visualize/analysis/test_stmt_traveler.py
Labels: backend, 테스트, if-else

#152 [#149]Test: expr들의 parse함수에 mock 처리 추가
  app/visualize/analysis/stmt/parser/expr/expr_traveler.py
  app/visualize/analysis/stmt/parser/expr/parser/call_expr.py
  app/visualize/analysis/stmt/parser/expr/parser/list_expr.py
  app/visualize/analysis/stmt/parser/expr/parser/name_expr.py
  poetry.lock
  pyproject.toml
  tests/visualize/analysis/stmt/parser/expr/parser/test_binop_expr.py
  tests/visualize/analysis/stmt/parser/expr/parser/test_call_expr.py
  tests/visualize/analysis/stmt/parser/expr/parser/test_constant_expr.py
  tests/visualize/analysis/stmt/parser/expr/parser/test_list_expr.py
  tests/visualize/analysis/stmt/parser/expr/parser/test_name_expr.py
  tests/visualize/utils/test_utils.py
Labels: test

#153 [#142]test: if-else Generator 테스트 코드 작성
  app/visualize/analysis/stmt/models/if_stmt_obj.py
  app/visualize/code_visualizer.py
  app/visualize/generator/converter/if_converter.py
  app/visualize/generator/converter_traveler.py
  app/visualize/generator/models/if_viz.py
  tests/conftest.py
  tests/visualize/generator/converter/test_if_converter.py
  tests/visualize/generator/test_converter_traveler.py
Labels: backend, 테스트, if-else

#154 [#145] slice 기능과 subscript 기능 구현
  app/visualize/analysis/stmt/parser/expr/expr_traveler.py
  app/visualize/analysis/stmt/parser/expr/models/expr_obj.py
  app/visualize/analysis/stmt/parser/expr/models/slice_expression.py
  app/visualize/analysis/stmt/parser/expr/parser/slice_expr.py
  app/visualize/analysis/stmt/parser/expr/parser/subscript_expr.py
  app/visualize/utils/utils.py
  tests/conftest.py
  tests/visualize/analysis/stmt/parser/expr/parser/test_name_expr.py
  tests/visualize/analysis/stmt/parser/expr/parser/test_slice_expr.py
  tests/visualize/analysis/stmt/parser/expr/parser/test_subscript_expr.py
Labels: feat, backend

#159 [#80]feat: 시각화에 Pass 기능 추가
  app/visualize/analysis/stmt/models/pass_stmt_obj.py
  app/visualize/analysis/stmt/parser/pass_stmt.py
  app/visualize/analysis/stmt/stmt_traveler.py
  app/visualize/generator/converter/flow_control_converter.py
  app/visualize/generator/converter_traveler.py
  app/visualize/generator/models/flow_control_viz.py
  tests/visualize/analysis/stmt/parser/test_pass_stmt.py
  tests/visualize/analysis/test_stmt_traveler.py
  tests/visualize/generator/converter/test_flow_control_converter.py
  tests/visualize/generator/test_converter_traveler.py
Labels: backend

#163 [#156, 157, 158]feat, refactor: 리스트 append 기능 구현 및 call 함수 분리
  app/visualize/analysis/stmt/models/assign_stmt_obj.py
  app/visualize/analysis/stmt/parser/expr/expr_traveler.py
  app/visualize/analysis/stmt/parser/expr/models/expr_obj.py
  app/visualize/analysis/stmt/parser/expr/parser/attr_func/append_expr.py
  app/visualize/analysis/stmt/parser/expr/parser/attribute_expr.py
  app/visualize/analysis/stmt/parser/expr/parser/built_in_func/print_expr.py
  app/visualize/analysis/stmt/parser/expr/parser/built_in_func/range_expr.py
  app/visualize/analysis/stmt/parser/expr/parser/call_expr.py
  app/visualize/analysis/stmt/parser/expr/parser/list_expr.py
  app/visualize/analysis/stmt/parser/expr/parser/slice_expr.py
  app/visualize/analysis/stmt/parser/expr/parser/subscript_expr.py
  app/visualize/generator/converter/assign_converter.py
  app/visualize/generator/converter/expr_converter.py
  app/visualize/generator/converter/if_converter.py
  app/visualize/generator/converter_traveler.py
  app/visualize/generator/models/append_viz.py
  app/visualize/generator/models/expr_viz.py
  app/visualize/generator/models/variable_vlz.py
  app/visualize/utils/utils.py
  tests/visualize/analysis/stmt/parser/expr/parser/attr_func/test_append_expr.py
  tests/visualize/analysis/stmt/parser/expr/parser/built_in_func/test_print_expr.py
  tests/visualize/analysis/stmt/parser/expr/parser/built_in_func/test_range_expr.py
  tests/visualize/analysis/stmt/parser/expr/parser/test_attribute_expr.py
  tests/visualize/analysis/stmt/parser/expr/parser/test_call_expr.py
  tests/visualize/analysis/stmt/parser/expr/parser/test_list_expr.py
  tests/visualize/generator/converter/test_assign_converter.py
Labels: feat, refactor, 테스트

#162 [#160]refactor: unitest의 mock에서 pytest의 목업을 사용
  tests/visualize/analysis/stmt/parser/test_for_stmt.py
  tests/visualize/analysis/stmt/parser/test_if_stmt.py
  tests/visualize/analysis/test_stmt_traveler.py
  tests/visualize/generator/converter/test_if_converter.py
  tests/visualize/generator/test_converter_traveler.py
Labels: backend, 테스트

#173 [#164]fix: called_once_with() -> assert_called_once_with()
  tests/visualize/analysis/stmt/parser/expr/parser/built_in_func/test_print_expr.py
  tests/visualize/analysis/stmt/parser/expr/parser/built_in_func/test_range_expr.py
  tests/visualize/analysis/stmt/parser/expr/parser/test_binop_expr.py
  tests/visualize/analysis/stmt/parser/expr/parser/test_call_expr.py
  tests/visualize/analysis/stmt/parser/expr/parser/test_constant_expr.py
  tests/visualize/analysis/stmt/parser/expr/parser/test_list_expr.py
  tests/visualize/analysis/stmt/parser/expr/parser/test_name_expr.py
  tests/visualize/analysis/stmt/parser/expr/parser/test_slice_expr.py
  tests/visualize/analysis/stmt/parser/expr/parser/test_subscript_expr.py
  tests/visualize/generator/converter/test_assign_converter.py
  tests/visualize/generator/converter/test_flow_control_converter.py
Labels: test, bug

#169 [#151]feat: ast.break 시각화 지원
  app/visualize/analysis/stmt/models/flow_control_obj.py
  app/visualize/analysis/stmt/models/if_stmt_obj.py
  app/visualize/analysis/stmt/parser/flow_control_stmt.py
  app/visualize/analysis/stmt/parser/for_stmt.py
  app/visualize/analysis/stmt/parser/pass_stmt.py
  app/visualize/analysis/stmt/stmt_traveler.py
  app/visualize/generator/converter/flow_control_converter.py
  app/visualize/generator/converter_traveler.py
  tests/conftest.py
  tests/visualize/analysis/stmt/parser/flow_control/test_break_stmt.py
  tests/visualize/analysis/stmt/parser/test_for_stmt.py
  tests/visualize/analysis/stmt/parser/test_pass_stmt.py
  tests/visualize/analysis/test_stmt_traveler.py
  tests/visualize/generator/converter/test_flow_control_converter.py
  tests/visualize/generator/converter/test_if_converter.py
  tests/visualize/generator/test_converter_traveler.py
Labels: feat

#174 [#161]refactor: 모든 Obj의 type을 String 타입에서 Enum 타입으로 변경
  app/visualize/analysis/stmt/models/assign_stmt_obj.py
  app/visualize/analysis/stmt/models/expr_stmt_obj.py
  app/visualize/analysis/stmt/models/flow_control_obj.py
  app/visualize/analysis/stmt/models/for_stmt_obj.py
  app/visualize/analysis/stmt/models/if_stmt_obj.py
  app/visualize/analysis/stmt/models/stmt_type.py
  app/visualize/analysis/stmt/parser/assign_stmt.py
  app/visualize/analysis/stmt/parser/expr/expr_traveler.py
  app/visualize/analysis/stmt/parser/expr/models/expr_obj.py
  app/visualize/analysis/stmt/parser/expr/models/expr_type.py
  app/visualize/analysis/stmt/parser/expr/parser/attribute_expr.py
  app/visualize/analysis/stmt/parser/expr/parser/call_expr.py
  app/visualize/analysis/stmt/parser/expr/parser/name_expr.py
  app/visualize/analysis/stmt/parser/flow_control_stmt.py
  app/visualize/analysis/stmt/parser/for_stmt.py
  app/visualize/generator/converter/assign_converter.py
  app/visualize/generator/converter/expr_converter.py
  app/visualize/generator/converter/flow_control_converter.py
  app/visualize/generator/converter/if_converter.py
  app/visualize/generator/converter_traveler.py
  app/visualize/generator/models/append_viz.py
  app/visualize/generator/models/assign_viz.py
  app/visualize/generator/models/expr_viz.py
  app/visualize/generator/models/for_viz.py
  app/visualize/generator/models/if_viz.py
  app/visualize/generator/models/print_viz.py
  app/visualize/utils/utils.py
  tests/visualize/analysis/stmt/parser/expr/parser/attr_func/test_append_expr.py
  tests/visualize/analysis/stmt/parser/expr/parser/built_in_func/test_range_expr.py
  tests/visualize/analysis/stmt/parser/expr/parser/test_attribute_expr.py
  tests/visualize/analysis/stmt/parser/expr/parser/test_binop_expr.py
  tests/visualize/analysis/stmt/parser/expr/parser/test_call_expr.py
  tests/visualize/analysis/stmt/parser/expr/parser/test_compare_expr.py
  tests/visualize/analysis/stmt/parser/expr/parser/test_list_expr.py
  tests/visualize/analysis/stmt/parser/expr/parser/test_name_expr.py
  tests/visualize/analysis/stmt/parser/expr/parser/test_slice_expr.py
  tests/visualize/analysis/stmt/parser/expr/parser/test_subscript_expr.py
  tests/visualize/analysis/stmt/parser/expr/parser/test_tuple_expr.py
  tests/visualize/analysis/stmt/parser/flow_control/test_break_stmt.py
  tests/visualize/analysis/stmt/parser/test_assign_stmt.py
  tests/visualize/analysis/stmt/parser/test_expr_stmt.py
  tests/visualize/analysis/stmt/parser/test_for_stmt.py
  tests/visualize/analysis/stmt/parser/test_pass_stmt.py
  tests/visualize/analysis/test_stmt_traveler.py
  tests/visualize/generator/converter/test_assign_converter.py
  tests/visualize/generator/converter/test_flow_control_converter.py
  tests/visualize/generator/converter/test_if_converter.py
  tests/visualize/generator/test_converter_traveler.py
Labels: refactor, BE

#175 [#172]bug: If, else 표현식(expr)의 하이라이트가 모든 인덱스가 받아짐
  app/visualize/generator/converter/expr_converter.py
  app/visualize/generator/highlight/expr_highlight.py
  tests/visualize/generator/highlight/test_expr_highlight.py
Labels: bug, BE

#178 [#150]feat: ast.Continue 지원
  app/visualize/analysis/stmt/models/flow_control_obj.py
  app/visualize/analysis/stmt/parser/flow_control_stmt.py
  app/visualize/analysis/stmt/parser/for_stmt.py
  app/visualize/analysis/stmt/stmt_traveler.py
  app/visualize/generator/converter/flow_control_converter.py
  tests/visualize/analysis/stmt/parser/test_flow_control_stmt.py
  tests/visualize/analysis/stmt/parser/test_for_stmt.py
  tests/visualize/analysis/stmt/parser/test_pass_stmt.py
  tests/visualize/analysis/test_stmt_traveler.py
Labels: feat, BE
