Repository edu-pi/Backend-Code-Analysis-Server, pull requests merged in 2024-06, with the labels that each got.

#29 [#16]test: Print문 하이라이트 추출 테스트
  app/analysis/highlight.py
  app/analysis/parser.py
  tests/__init__.py
  tests/test_highlight.py
Labels: backend, test

#62 [#52] 기존 BinOp로직을 bin op_parser.py에 분리
  app/analysis/generator/parser/binop_parser.py
  app/analysis/parser1.py
  app/analysis/util/util.py
Labels: refactor

#63 [#55]refactor: assign에 대한 로직 assign_generator로 이동
  app/analysis/code_analyzer.py
  app/analysis/generator/assign_generator.py
  app/analysis/models.py
  app/analysis/parser1.py
Labels: refactor

#65 [#54]refactor: 기존에 있던 tuple로직 분리와 tuple이 들어오면서 생긴 변경사항 추가
  app/analysis/code_analyzer.py
  app/analysis/generator/assign_generator.py
  app/analysis/generator/parser/binop_parser.py
  app/analysis/generator/parser/constant_parser.py
  app/analysis/generator/parser/name_parser.py
  app/analysis/generator/parser/tuple_parser.py
  app/analysis/parser1.py
Labels: refactor

#64 [#61]refactor: 기존 print블록 로직을 Expr_generator.py, call_parser.py로 분리 #61
  app/analysis/code_analyzer.py
  app/analysis/generator/expr_generator.py
  app/analysis/generator/parser/call_parser.py
  app/analysis/models.py
  tests/test_call_parser.py
Labels: refactor

#70 [#49]refactor: 기존 For블록 로직을 for_generator.py로 분리
  app/analysis/code_analyzer.py
  app/analysis/generator/expr_generator.py
  app/analysis/generator/for_generator.py
  app/analysis/generator/highlight/__init__.py
  app/analysis/generator/highlight/for_highlight.py
  app/analysis/generator/parser/call_parser.py
  app/analysis/models.py
  app/analysis/parser1.py
Labels: backend, refactor

#71 [#45]fix: '//' 연산 지원 안됨
  app/analysis/generator/for_generator.py
  app/analysis/generator/highlight/for_highlight.py
  app/analysis/generator/parser/binop_parser.py
  app/analysis/highlight.py
  app/analysis/models.py
Labels: fix, 별찍기

#76 [#75]fix: printViz의 id 생성할 떄 노드 기준으로 생성하도록 변경, __call_id 추가
  app/analysis/generator/expr_generator.py
Labels: fix, 별찍기

#79 [#77]test: ConstantParser 테스트 코드 작성
  app/analysis/generator/parser/constant_parser.py
  tests/analysis/generator/parser/test_constant_parser.py
  tests/analysis/generator/parser/test_name_parser.py
  tests/test_call_parser.py
Labels: backend, test

#81 [#78]test: test_call_parser.py 위치 변경과, BinopParser의 테스트코드 작성
  app/analysis/generator/parser/binop_parser.py
  tests/analysis/generator/parser/test_binop_parser.py
  tests/analysis/generator/parser/test_call_parser.py
Labels: backend, test

#83 [#82]test: TupleParser에 대한 테스트 코드 작성
  app/analysis/util/util.py
  tests/analysis/generator/parser/test_tuple_parser.py
Labels: backend, test

#86 [#36]feat: front와 연결하기 위해 cors 에러를 해결, 입력받는 request 데이터 정의
  app/route.py
Labels: feat

#94 [Test] for_generator 테스트 코드 작성
  .gitignore
  app/analysis/generator/for_generator.py
  tests/analysis/generator/parser/test_data/for_generator_data.py
  tests/analysis/generator/test_for_generator.py
Labels: test

#99 [#97] refactor: for문 파싱 로직 decoupling
  app/analysis/generator/assign_generator.py
  app/analysis/generator/for_generator.py
  app/route.py
  app/visualize/analysis/element_manager.py
  app/visualize/analysis/stmt/expr/expr_util/util.py
  app/visualize/analysis/stmt/expr/parser/name_expr.py
  app/visualize/analysis/stmt/model/for_stmt_obj.py
  app/visualize/analysis/stmt/parser/for_stmt.py
  app/visualize/analysis/stmt/stmt_traveler.py
  app/visualize/code_analyzer.py
  app/visualize/generator/model/models.py
  tests/visualize/analysis/stmt/parser/test_for_stmt.py
Labels: backend, decoupling

#98 [#92] feat: assign_stmt 기능 작성
  app/visualize/analysis/stmt/expr/parser/binop_expr.py
  app/visualize/analysis/stmt/parser/assign_stmt.py
  app/visualize/analysis/stmt/stmt_traveler.py
Labels: backend, decoupling

#101 [#100] refactor: Expr Stmt 로직 분리
  app/route.py
  app/visualize/analysis/stmt/expr/expr_traveler.py
  app/visualize/analysis/stmt/model/expr_stmt_obj.py
  app/visualize/analysis/stmt/parser/assign_stmt.py
  app/visualize/analysis/stmt/parser/expr_stmt.py
  app/visualize/analysis/stmt/stmt_traveler.py
  app/visualize/code_visualizer.py
  tests/conftest.py
  tests/visualize/analysis/stmt/parser/test_expr_stmt.py
Labels: backend, decoupling

#108 [#106]feat: generator 폴더 구조 생성
  app/visualize/generator/converter/assign_converter.py
  app/visualize/generator/converter/expr_converter.py
  app/visualize/generator/converter/for_converter.py
  app/visualize/generator/converter/print_converter.py
  app/visualize/generator/converter_traveler.py
  tests/visualize/analysis/stmt/parser/test_expr_stmt.py
Labels: backend, decoupling
