Repository edu-pi/Backend-Code-Analysis-Server, pull requests merged in 2024-08, with the labels that each got.

#192 [#177]feat: mod연산 지원 기능과 테스트 추가
  app/visualize/analysis/stmt/parser/expr/parser/binop_expr.py
  tests/visualize/analysis/stmt/parser/expr/parser/test_binop_expr.py
Labels: bug, BE

#195 [#194]fix: ExprStmt에 type을 바꾸는 과정에서 expr로 고정되는 문제
  app/visualize/analysis/stmt/parser/assign_stmt.py
  app/visualize/generator/converter/expr_converter.py
  app/visualize/generator/models/expr_viz.py
Labels: bug, BE

#197 [#196]fix: 프론트에서 API 요청시 잘못된 데이터 타입으로 받는 에러 수정
  app/route.py
  app/visualize/code_visualizer.py
Labels: bug, BE

#199 [#198]fix: ForConditionViz의 필드를 int -> str로 변경
  app/visualize/generator/models/for_viz.py
Labels: bug, BE

#191 [#188]feat: while문 기능 구현
  app/visualize/analysis/stmt/models/stmt_type.py
  app/visualize/analysis/stmt/models/while_stmt_obj.py
  app/visualize/analysis/stmt/parser/expr/parser/compare_expr.py
  app/visualize/analysis/stmt/parser/if_stmt.py
  app/visualize/analysis/stmt/parser/while_stmt.py
  app/visualize/analysis/stmt/stmt_traveler.py
  app/visualize/generator/converter/if_converter.py
  app/visualize/generator/converter/while_converter.py
  app/visualize/generator/converter_traveler.py
  app/visualize/generator/models/if_viz.py
  app/visualize/generator/models/while_viz.py
  tests/visualize/analysis/stmt/parser/expr/parser/test_compare_expr.py
  tests/visualize/analysis/stmt/parser/test_if_stmt.py
  tests/visualize/generator/converter/test_if_converter.py
Labels: feat, BE

#200 [#187]test: ast.While문에 대한 테스트 코드 작성
  app/visualize/analysis/stmt/models/expr_stmt_obj.py
  app/visualize/analysis/stmt/parser/if_stmt.py
  app/visualize/analysis/stmt/parser/while_stmt.py
  app/visualize/analysis/stmt/stmt_traveler.py
  app/visualize/generator/converter/while_converter.py
  app/visualize/generator/converter_traveler.py
  tests/visualize/analysis/stmt/parser/test_if_stmt.py
  tests/visualize/analysis/stmt/parser/test_while_stmt.py
  tests/visualize/analysis/test_stmt_traveler.py
  tests/visualize/generator/converter/test_expr_converter.py
Labels: test, BE

#203 [#202]fix: while문 body에 들어가면 depth가 증가하지 않는 문제 해결 및 orelse 추가
  app/visualize/analysis/stmt/models/while_stmt_obj.py
  app/visualize/analysis/stmt/stmt_traveler.py
  app/visualize/generator/converter/while_converter.py
  app/visualize/generator/converter_traveler.py
  app/visualize/generator/models/while_viz.py
  tests/visualize/analysis/test_stmt_traveler.py
Labels: bug, BE

#206 [#205]feat: 라인 수 에 해당되는 코드를 모든 Viz 데이터에 추가
  app/visualize/code_visualizer.py
  app/visualize/generator/converter/assign_converter.py
  app/visualize/generator/converter/expr_converter.py
  app/visualize/generator/converter/flow_control_converter.py
  app/visualize/generator/converter/for_header_converter.py
  app/visualize/generator/converter/if_converter.py
  app/visualize/generator/converter/while_converter.py
  app/visualize/generator/converter_traveler.py
  app/visualize/generator/models/expr_viz.py
  app/visualize/generator/models/flow_control_viz.py
  app/visualize/generator/models/for_viz.py
  app/visualize/generator/models/if_viz.py
  app/visualize/generator/models/print_viz.py
  app/visualize/generator/models/variable_vlz.py
  app/visualize/generator/models/while_viz.py
  app/visualize/generator/visualization_manager.py
  tests/visualize/generator/converter/test_assign_converter.py
  tests/visualize/generator/converter/test_expr_converter.py
  tests/visualize/generator/converter/test_flow_control_converter.py
  tests/visualize/generator/converter/test_if_converter.py
  tests/visualize/generator/test_converter_traveler.py
  tests/visualize/generator/test_visualzation_manager.py
Labels: feat, BE

#212 [#211]fix: ifViz에 code 속성 추가
  app/visualize/generator/converter/if_converter.py
  app/visualize/generator/models/if_viz.py
  tests/conftest.py
  tests/visualize/generator/converter/test_if_converter.py
Labels: bug, BE

#224 [Feat] string fommat 기능 추가
  app/visualize/analysis/stmt/parser/expr/expr_traveler.py
  app/visualize/analysis/stmt/parser/expr/models/expr_obj.py
  app/visualize/analysis/stmt/parser/expr/parser/formatted_value_expr.py
  app/visualize/analysis/stmt/parser/expr/parser/joined_str_expr.py
  tests/visualize/analysis/stmt/parser/expr/parser/test_formatted_value_expr.py
  tests/visualize/analysis/stmt/parser/expr/parser/test_joined_str_expr.py
  tests/visualize/analysis/stmt/parser/test_while_stmt.py
Labels: feat, BE
